config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # verb '/path', to: 'controller#action'

  # READ ALL
  get '/restaurants', to: 'restaurants#index', as: 'restaurants'

  # CREATE 2 STEPS
  # NEW
  get '/restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
  # CREATE
  post '/restaurants', to: 'restaurants#create'


  # UPDATE
  # Display the form
  get '/restaurants/:id/edit', to: 'restaurants#edit', as: 'edit_restaurant'
  # receive the form
  patch '/restaurants/:id', to: 'restaurants#update'

  # READ ONE
  get '/restaurants/:id', to: 'restaurants#show', as: 'restaurant'
  delete '/restaurants/:id', to: 'restaurants#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
    # DOESN'T HAVE A VIEW
    redirect_to restaurant_path(restaurant) # "/restaurants/#{restaurant.id}"
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    # DOESN'T HAVE A VIEW
    redirect_to restaurants_path
  end

  def destroy
    # find the right restaurant
    # call the destroy method on it to remove from the DB
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # {"authenticity_token"=>"[FILTERED]", "restaurant"=>{"name"=>"Burger Palce", "address"=>"London", "rating"=>"5"}, "commit"=>"Create Restaurant"}
  # "restaurant"=>{"name"=>"Burger Palce", "address"=>"London", "rating"=>"5"}
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud1182</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants Index</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

<%= link_to 'New restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Address: <%= @restaurant.address %></p>
<p>Rating: <%= @restaurant.rating %></p>


<%#= link_to 'TEXT', PATH %>
<%= link_to 'Back to restaurants', restaurants_path %> |
<%= link_to 'Edit this restaurant', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Delete this restaurant', restaurant_path(@restaurant), data: { turbo_method: 'DELETE', turbo_confirm: 'Are you sure???' } %>